// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UpravlenieRC.Server.Models;

public partial class Arrival
{
    public int Id { get; set; }

    public int Idstatus { get; set; }

    public int? Idpartner { get; set; }

    public int Creator { get; set; }

    public int? DepartedFromid { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? ArrivedAt { get; set; }

    public DateTime? AsseptedAt { get; set; }

    public int? Iddriver { get; set; }

    public int? IdAcceptanceClerk { get; set; }

    public string Notes { get; set; }

    public string CarPlate { get; set; }

    public virtual User CreatorNavigation { get; set; }

    public virtual DirectionPoint DepartedFrom { get; set; }

    public virtual User IdAcceptanceClerkNavigation { get; set; }

    public virtual Driver IddriverNavigation { get; set; }

    public virtual Status IdstatusNavigation { get; set; }

    public virtual ICollection<ReturnArrival> ReturnArrivals { get; set; } = new List<ReturnArrival>();

    public virtual ICollection<TovarArrival> TovarArrivals { get; set; } = new List<TovarArrival>();
}