// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UpravlenieRC.Server.Models;

public partial class CellBalance
{
    public int Id { get; set; }

    public int Idcell { get; set; }

    public int Idtovar { get; set; }

    public double Amount { get; set; }

    public virtual StorageCell IdcellNavigation { get; set; }

    public virtual Tovar IdtovarNavigation { get; set; }
}