// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UpravlenieRC.Server.Models;

public partial class DirectionPoint
{
    public int Id { get; set; }

    public int Idowner { get; set; }

    public string Address { get; set; }

    public virtual ICollection<Arrival> Arrivals { get; set; } = new List<Arrival>();

    public virtual Partner IdownerNavigation { get; set; }

    public virtual ICollection<Outbound> Outbounds { get; set; } = new List<Outbound>();
}