// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UpravlenieRC.Server.Models;

public partial class Driver
{
    public int Id { get; set; }

    public int? Iduser { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Arrival> Arrivals { get; set; } = new List<Arrival>();

    public virtual User IduserNavigation { get; set; }

    public virtual ICollection<Outbound> Outbounds { get; set; } = new List<Outbound>();
}