// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UpravlenieRC.Server.Models;

public partial class Good
{
    public int Id { get; set; }

    public int IdCategory { get; set; }

    public int Idunits { get; set; }

    public int Idmanufacturer { get; set; }

    public double? Maxtemperature { get; set; }

    public double? Mintemperature { get; set; }

    public double VolumeForOneUnit { get; set; }

    public double WeightForOneUnit { get; set; }

    public virtual TovarCategory IdCategoryNavigation { get; set; }

    public virtual Manufacturer IdmanufacturerNavigation { get; set; }

    public virtual Unit IdunitsNavigation { get; set; }

    public virtual ICollection<Tovar> Tovars { get; set; } = new List<Tovar>();
}