// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UpravlenieRC.Server.Models;

public partial class InternalMovement
{
    public int Id { get; set; }

    public int IdOldCell { get; set; }

    public int IdNewCell { get; set; }

    public DateTime Date { get; set; }

    public virtual StorageCell IdNewCellNavigation { get; set; }

    public virtual StorageCell IdOldCellNavigation { get; set; }

    public virtual ICollection<TovarInternalMovenent> TovarInternalMovenents { get; set; } = new List<TovarInternalMovenent>();
}