// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UpravlenieRC.Server.Models;

public partial class Outbound
{
    public int Id { get; set; }

    public int Idstatus { get; set; }

    public int Creator { get; set; }

    public int Destinationid { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? LoadedAt { get; set; }

    public DateTime? ArrivedAt { get; set; }

    public string CarPlate { get; set; }

    public int? Iddriver { get; set; }

    public string Notes { get; set; }

    public virtual User CreatorNavigation { get; set; }

    public virtual DirectionPoint Destination { get; set; }

    public virtual Driver IddriverNavigation { get; set; }

    public virtual Status IdstatusNavigation { get; set; }

    public virtual ICollection<ReturnOutbound> ReturnOutbounds { get; set; } = new List<ReturnOutbound>();

    public virtual ICollection<TovarOutbound> TovarOutbounds { get; set; } = new List<TovarOutbound>();
}