// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace UpravlenieRC.Server.Models;

public partial class RC_SkladContext : DbContext
{
    public RC_SkladContext()
    {
    }

    public RC_SkladContext(DbContextOptions<RC_SkladContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Arrival> Arrivals { get; set; }

    public virtual DbSet<CellBalance> CellBalances { get; set; }

    public virtual DbSet<DirectionPoint> DirectionPoints { get; set; }

    public virtual DbSet<Driver> Drivers { get; set; }

    public virtual DbSet<Good> Goods { get; set; }

    public virtual DbSet<InternalMovement> InternalMovements { get; set; }

    public virtual DbSet<Manufacturer> Manufacturers { get; set; }

    public virtual DbSet<Outbound> Outbounds { get; set; }

    public virtual DbSet<Partner> Partners { get; set; }

    public virtual DbSet<Return> Returns { get; set; }

    public virtual DbSet<ReturnArrival> ReturnArrivals { get; set; }

    public virtual DbSet<ReturnOutbound> ReturnOutbounds { get; set; }

    public virtual DbSet<Status> Statuses { get; set; }

    public virtual DbSet<StorageCell> StorageCells { get; set; }

    public virtual DbSet<Tovar> Tovars { get; set; }

    public virtual DbSet<TovarArrival> TovarArrivals { get; set; }

    public virtual DbSet<TovarCategory> TovarCategories { get; set; }

    public virtual DbSet<TovarCellHistory> TovarCellHistories { get; set; }

    public virtual DbSet<TovarInternalMovenent> TovarInternalMovenents { get; set; }

    public virtual DbSet<TovarOutbound> TovarOutbounds { get; set; }

    public virtual DbSet<TovarReturn> TovarReturns { get; set; }

    public virtual DbSet<Unit> Units { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserType> UserTypes { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseLazyLoadingProxies().UseSqlServer("Data Source=MAIN_NOTEBOOK;Initial Catalog=RC_Sklad;Integrated Security=True;Encrypt=True;Trust Server Certificate=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Arrival>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__arrival__3213E83F5579AE8B");

            entity.ToTable("arrival");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.ArrivedAt)
                .HasColumnType("datetime")
                .HasColumnName("arrivedAt");
            entity.Property(e => e.AsseptedAt)
                .HasColumnType("datetime")
                .HasColumnName("asseptedAt");
            entity.Property(e => e.CarPlate)
                .HasMaxLength(18)
                .HasColumnName("carPlate");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.Creator).HasColumnName("creator");
            entity.Property(e => e.DepartedFromid).HasColumnName("departedFromid");
            entity.Property(e => e.IdAcceptanceClerk).HasColumnName("idAcceptanceClerk");
            entity.Property(e => e.Iddriver).HasColumnName("iddriver");
            entity.Property(e => e.Idpartner).HasColumnName("idpartner");
            entity.Property(e => e.Idstatus).HasColumnName("idstatus");
            entity.Property(e => e.Notes)
                .HasMaxLength(255)
                .HasColumnName("notes");

            entity.HasOne(d => d.CreatorNavigation).WithMany(p => p.ArrivalCreatorNavigations)
                .HasForeignKey(d => d.Creator)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__arrival__creator__02084FDA");

            entity.HasOne(d => d.DepartedFrom).WithMany(p => p.Arrivals)
                .HasForeignKey(d => d.DepartedFromid)
                .HasConstraintName("FK__arrival__departe__7F2BE32F");

            entity.HasOne(d => d.IdAcceptanceClerkNavigation).WithMany(p => p.ArrivalIdAcceptanceClerkNavigations)
                .HasForeignKey(d => d.IdAcceptanceClerk)
                .HasConstraintName("FK__arrival__idAccep__05D8E0BE");

            entity.HasOne(d => d.IddriverNavigation).WithMany(p => p.Arrivals)
                .HasForeignKey(d => d.Iddriver)
                .HasConstraintName("FK__arrival__iddrive__02FC7413");

            entity.HasOne(d => d.IdstatusNavigation).WithMany(p => p.Arrivals)
                .HasForeignKey(d => d.Idstatus)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__arrival__idstatu__75A278F5");
        });

        modelBuilder.Entity<CellBalance>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__cellBala__3213E83F34F11EA6");

            entity.ToTable("cellBalance");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Amount).HasColumnName("amount");
            entity.Property(e => e.Idcell).HasColumnName("idcell");
            entity.Property(e => e.Idtovar).HasColumnName("idtovar");

            entity.HasOne(d => d.IdcellNavigation).WithMany(p => p.CellBalances)
                .HasForeignKey(d => d.Idcell)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__cellBalan__idcel__66603565");

            entity.HasOne(d => d.IdtovarNavigation).WithMany(p => p.CellBalances)
                .HasForeignKey(d => d.Idtovar)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__cellBalan__idtov__656C112C");
        });

        modelBuilder.Entity<DirectionPoint>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__directio__3213E83F4A65F036");

            entity.ToTable("directionPoint");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Address)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("address");
            entity.Property(e => e.Idowner).HasColumnName("idowner");

            entity.HasOne(d => d.IdownerNavigation).WithMany(p => p.DirectionPoints)
                .HasForeignKey(d => d.Idowner)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__direction__idown__7E37BEF6");
        });

        modelBuilder.Entity<Driver>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__driver__3213E83FDCEE2625");

            entity.ToTable("driver");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Iduser).HasColumnName("iduser");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("name");

            entity.HasOne(d => d.IduserNavigation).WithMany(p => p.Drivers)
                .HasForeignKey(d => d.Iduser)
                .HasConstraintName("FK__driver__iduser__04E4BC85");
        });

        modelBuilder.Entity<Good>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__goods__3213E83FA191D5D9");

            entity.ToTable("goods");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.IdCategory).HasColumnName("idCategory");
            entity.Property(e => e.Idmanufacturer).HasColumnName("idmanufacturer");
            entity.Property(e => e.Idunits).HasColumnName("idunits");
            entity.Property(e => e.Maxtemperature)
                .HasDefaultValue(50.0)
                .HasColumnName("maxtemperature");
            entity.Property(e => e.Mintemperature)
                .HasDefaultValue(-40.0)
                .HasColumnName("mintemperature");
            entity.Property(e => e.VolumeForOneUnit).HasColumnName("volumeForOneUnit");
            entity.Property(e => e.WeightForOneUnit).HasColumnName("weightForOneUnit");

            entity.HasOne(d => d.IdCategoryNavigation).WithMany(p => p.Goods)
                .HasForeignKey(d => d.IdCategory)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__goods__idCategor__693CA210");

            entity.HasOne(d => d.IdmanufacturerNavigation).WithMany(p => p.Goods)
                .HasForeignKey(d => d.Idmanufacturer)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__goods__idmanufac__787EE5A0");

            entity.HasOne(d => d.IdunitsNavigation).WithMany(p => p.Goods)
                .HasForeignKey(d => d.Idunits)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__goods__idunits__778AC167");
        });

        modelBuilder.Entity<InternalMovement>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__internal__3213E83F15A00E01");

            entity.ToTable("internalMovement");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Date)
                .HasColumnType("datetime")
                .HasColumnName("date");
            entity.Property(e => e.IdNewCell).HasColumnName("idNewCell");
            entity.Property(e => e.IdOldCell).HasColumnName("idOldCell");

            entity.HasOne(d => d.IdNewCellNavigation).WithMany(p => p.InternalMovementIdNewCellNavigations)
                .HasForeignKey(d => d.IdNewCell)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__internalM__idNew__73BA3083");

            entity.HasOne(d => d.IdOldCellNavigation).WithMany(p => p.InternalMovementIdOldCellNavigations)
                .HasForeignKey(d => d.IdOldCell)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__internalM__idOld__74AE54BC");
        });

        modelBuilder.Entity<Manufacturer>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__manufact__3213E83F05FAB727");

            entity.ToTable("manufacturer");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Address)
                .HasMaxLength(255)
                .HasColumnName("address");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("name");
        });

        modelBuilder.Entity<Outbound>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__outbound__3213E83FA7ED20F5");

            entity.ToTable("outbound");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.ArrivedAt)
                .HasColumnType("datetime")
                .HasColumnName("arrivedAt");
            entity.Property(e => e.CarPlate)
                .HasMaxLength(255)
                .HasColumnName("carPlate");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.Creator).HasColumnName("creator");
            entity.Property(e => e.Destinationid).HasColumnName("destinationid");
            entity.Property(e => e.Iddriver).HasColumnName("iddriver");
            entity.Property(e => e.Idstatus).HasColumnName("idstatus");
            entity.Property(e => e.LoadedAt)
                .HasColumnType("datetime")
                .HasColumnName("loadedAt");
            entity.Property(e => e.Notes)
                .HasMaxLength(255)
                .HasColumnName("notes");

            entity.HasOne(d => d.CreatorNavigation).WithMany(p => p.Outbounds)
                .HasForeignKey(d => d.Creator)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__outbound__creato__01142BA1");

            entity.HasOne(d => d.Destination).WithMany(p => p.Outbounds)
                .HasForeignKey(d => d.Destinationid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__outbound__destin__00200768");

            entity.HasOne(d => d.IddriverNavigation).WithMany(p => p.Outbounds)
                .HasForeignKey(d => d.Iddriver)
                .HasConstraintName("FK__outbound__iddriv__03F0984C");

            entity.HasOne(d => d.IdstatusNavigation).WithMany(p => p.Outbounds)
                .HasForeignKey(d => d.Idstatus)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__outbound__idstat__76969D2E");
        });

        modelBuilder.Entity<Partner>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__partner__3213E83F57D92076");

            entity.ToTable("partner");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Address)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("address");
            entity.Property(e => e.Iin)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("IIN");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("name");
        });

        modelBuilder.Entity<Return>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__returns__3213E83FD46D0471");

            entity.ToTable("returns");

            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnName("id");
            entity.Property(e => e.ReturnedAt)
                .HasColumnType("datetime")
                .HasColumnName("returnedAt");

            entity.HasOne(d => d.IdNavigation).WithOne(p => p.Return)
                .HasForeignKey<Return>(d => d.Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__returns__id__797309D9");

            entity.HasOne(d => d.Id1).WithOne(p => p.Return)
                .HasForeignKey<Return>(d => d.Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__returns__id__7A672E12");
        });

        modelBuilder.Entity<ReturnArrival>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__returnAr__3213E83FCED9177F");

            entity.ToTable("returnArrival");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.Idarrival).HasColumnName("idarrival");

            entity.HasOne(d => d.IdarrivalNavigation).WithMany(p => p.ReturnArrivals)
                .HasForeignKey(d => d.Idarrival)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__returnArr__idarr__7B5B524B");
        });

        modelBuilder.Entity<ReturnOutbound>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__returnOu__3213E83F06E6403E");

            entity.ToTable("returnOutbound");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.Idoutbound).HasColumnName("idoutbound");

            entity.HasOne(d => d.IdoutboundNavigation).WithMany(p => p.ReturnOutbounds)
                .HasForeignKey(d => d.Idoutbound)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__returnOut__idout__7C4F7684");
        });

        modelBuilder.Entity<Status>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__status__3213E83F247FDB35");

            entity.ToTable("status");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("name");
        });

        modelBuilder.Entity<StorageCell>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__storageC__3213E83F3025CCF8");

            entity.ToTable("storageCell");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Column).HasColumnName("column");
            entity.Property(e => e.Maxvolume).HasColumnName("maxvolume");
            entity.Property(e => e.Maxweight).HasColumnName("maxweight");
            entity.Property(e => e.Row).HasColumnName("row");
            entity.Property(e => e.Temperature)
                .HasDefaultValue(22.0)
                .HasColumnName("temperature");
        });

        modelBuilder.Entity<Tovar>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tovar__3213E83F448D5C6C");

            entity.ToTable("tovar");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.BatchNumber)
                .HasMaxLength(255)
                .HasColumnName("batchNumber");
            entity.Property(e => e.ExpirationDate).HasColumnType("datetime");
            entity.Property(e => e.Idgood).HasColumnName("idgood");
            entity.Property(e => e.Notes)
                .HasMaxLength(255)
                .HasColumnName("notes");

            entity.HasOne(d => d.IdgoodNavigation).WithMany(p => p.Tovars)
                .HasForeignKey(d => d.Idgood)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__tovar__idgood__6754599E");
        });

        modelBuilder.Entity<TovarArrival>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tovar_ar__3213E83F7BE8F0C7");

            entity.ToTable("tovar_arrival");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Amount).HasColumnName("amount");
            entity.Property(e => e.Arrival).HasColumnName("arrival");
            entity.Property(e => e.Isgood).HasColumnName("isgood");
            entity.Property(e => e.Tovar).HasColumnName("tovar");

            entity.HasOne(d => d.ArrivalNavigation).WithMany(p => p.TovarArrivals)
                .HasForeignKey(d => d.Arrival)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__tovar_arr__arriv__6EF57B66");

            entity.HasOne(d => d.TovarNavigation).WithMany(p => p.TovarArrivals)
                .HasForeignKey(d => d.Tovar)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__tovar_arr__tovar__6A30C649");
        });

        modelBuilder.Entity<TovarCategory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tovarCat__3213E83FF5E6CFA9");

            entity.ToTable("tovarCategory");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("name");
        });

        modelBuilder.Entity<TovarCellHistory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tovar_ce__3213E83FF065C1F8");

            entity.ToTable("tovar_cell_history");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Amount).HasColumnName("amount");
            entity.Property(e => e.Cell).HasColumnName("cell");
            entity.Property(e => e.Tovar).HasColumnName("tovar");

            entity.HasOne(d => d.CellNavigation).WithMany(p => p.TovarCellHistories)
                .HasForeignKey(d => d.Cell)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__tovar_cell__cell__6FE99F9F");

            entity.HasOne(d => d.TovarNavigation).WithMany(p => p.TovarCellHistories)
                .HasForeignKey(d => d.Tovar)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__tovar_cel__tovar__6B24EA82");
        });

        modelBuilder.Entity<TovarInternalMovenent>(entity =>
        {
            entity.HasKey(e => new { e.Tovar, e.InternalMovement });

            entity.ToTable("tovar_internalMovenent");

            entity.Property(e => e.Tovar).HasColumnName("tovar");
            entity.Property(e => e.InternalMovement).HasColumnName("internalMovement");
            entity.Property(e => e.Amount).HasColumnName("amount");

            entity.HasOne(d => d.InternalMovementNavigation).WithMany(p => p.TovarInternalMovenents)
                .HasForeignKey(d => d.InternalMovement)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__tovar_int__inter__72C60C4A");

            entity.HasOne(d => d.TovarNavigation).WithMany(p => p.TovarInternalMovenents)
                .HasForeignKey(d => d.Tovar)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__tovar_int__tovar__6E01572D");
        });

        modelBuilder.Entity<TovarOutbound>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tovar_ou__3213E83FD1051435");

            entity.ToTable("tovar_outbound");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Amount).HasColumnName("amount");
            entity.Property(e => e.Isgood).HasColumnName("isgood");
            entity.Property(e => e.Outbound).HasColumnName("outbound");
            entity.Property(e => e.Tovar).HasColumnName("tovar");

            entity.HasOne(d => d.OutboundNavigation).WithMany(p => p.TovarOutbounds)
                .HasForeignKey(d => d.Outbound)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__tovar_out__outbo__71D1E811");

            entity.HasOne(d => d.TovarNavigation).WithMany(p => p.TovarOutbounds)
                .HasForeignKey(d => d.Tovar)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__tovar_out__tovar__6D0D32F4");
        });

        modelBuilder.Entity<TovarReturn>(entity =>
        {
            entity.HasKey(e => new { e.Tovar, e.Returnid });

            entity.ToTable("tovar_return");

            entity.Property(e => e.Tovar).HasColumnName("tovar");
            entity.Property(e => e.Returnid).HasColumnName("returnid");
            entity.Property(e => e.Amount).HasColumnName("amount");

            entity.HasOne(d => d.Return).WithMany(p => p.TovarReturns)
                .HasForeignKey(d => d.Returnid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__tovar_ret__retur__70DDC3D8");

            entity.HasOne(d => d.TovarNavigation).WithMany(p => p.TovarReturns)
                .HasForeignKey(d => d.Tovar)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__tovar_ret__tovar__6C190EBB");
        });

        modelBuilder.Entity<Unit>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__units__3213E83F1245E89F");

            entity.ToTable("units");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("name");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__user__3213E83F3DF1470C");

            entity.ToTable("user");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("email");
            entity.Property(e => e.Idpartner).HasColumnName("idpartner");
            entity.Property(e => e.Idtype).HasColumnName("idtype");
            entity.Property(e => e.Login)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("login");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("password");
            entity.Property(e => e.Phone)
                .HasMaxLength(255)
                .HasColumnName("phone");

            entity.HasOne(d => d.IdpartnerNavigation).WithMany(p => p.Users)
                .HasForeignKey(d => d.Idpartner)
                .HasConstraintName("FK__user__idpartner__7D439ABD");

            entity.HasOne(d => d.IdtypeNavigation).WithMany(p => p.Users)
                .HasForeignKey(d => d.Idtype)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__user__idtype__68487DD7");
        });

        modelBuilder.Entity<UserType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__userType__3213E83F85576E4C");

            entity.ToTable("userType");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("name");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}