// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UpravlenieRC.Server.Models;

public partial class ReturnArrival : Return
{
    public int Idarrival { get; set; }

    public virtual Arrival IdarrivalNavigation { get; set; }

    public virtual Return Return { get; set; }
}