// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UpravlenieRC.Server.Models;

public partial class ReturnOutbound : Return
{
    public int Idoutbound { get; set; }

    public virtual Outbound IdoutboundNavigation { get; set; }

    public virtual Return Return { get; set; }
}