// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UpravlenieRC.Server.Models;

public partial class Return
{
    public int Id { get; set; }

    public DateTime? ReturnedAt { get; set; }

    public virtual ReturnOutbound Id1 { get; set; }

    public virtual ReturnArrival IdNavigation { get; set; }

    public virtual ICollection<TovarReturn> TovarReturns { get; set; } = new List<TovarReturn>();
}