// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UpravlenieRC.Server.Models;

public partial class StorageCell
{
    public int Id { get; set; }

    public int Row { get; set; }

    public int Column { get; set; }

    public double? Temperature { get; set; }

    public double Maxvolume { get; set; }

    public double Maxweight { get; set; }

    public virtual ICollection<CellBalance> CellBalances { get; set; } = new List<CellBalance>();

    public virtual ICollection<InternalMovement> InternalMovementIdNewCellNavigations { get; set; } = new List<InternalMovement>();

    public virtual ICollection<InternalMovement> InternalMovementIdOldCellNavigations { get; set; } = new List<InternalMovement>();

    public virtual ICollection<TovarCellHistory> TovarCellHistories { get; set; } = new List<TovarCellHistory>();
}