// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UpravlenieRC.Server.Models;

public partial class TovarInternalMovenent
{
    public int Tovar { get; set; }

    public int InternalMovement { get; set; }

    public double Amount { get; set; }

    public virtual InternalMovement InternalMovementNavigation { get; set; }

    public virtual Tovar TovarNavigation { get; set; }
}