// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UpravlenieRC.Server.Models;

public partial class TovarOutbound
{
    public int Id { get; set; }

    public int Tovar { get; set; }

    public int Outbound { get; set; }

    public bool? Isgood { get; set; }

    public double Amount { get; set; }

    public virtual Outbound OutboundNavigation { get; set; }

    public virtual Tovar TovarNavigation { get; set; }
}