// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UpravlenieRC.Server.Models;

public partial class Tovar
{
    public int Id { get; set; }

    public int Idgood { get; set; }

    public string BatchNumber { get; set; }

    public DateTime ExpirationDate { get; set; }

    public string Notes { get; set; }

    public virtual ICollection<CellBalance> CellBalances { get; set; } = new List<CellBalance>();

    public virtual Good IdgoodNavigation { get; set; }

    public virtual ICollection<TovarArrival> TovarArrivals { get; set; } = new List<TovarArrival>();

    public virtual ICollection<TovarCellHistory> TovarCellHistories { get; set; } = new List<TovarCellHistory>();

    public virtual ICollection<TovarOutbound> TovarOutbounds { get; set; } = new List<TovarOutbound>();

    public virtual ICollection<TovarReturn> TovarReturns { get; set; } = new List<TovarReturn>();
}