// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UpravlenieRC.Server.Models;

public partial class Unit
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Good> Goods { get; set; } = new List<Good>();
}