// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UpravlenieRC.Server.Models;

public partial class User
{
    public int Id { get; set; }

    public int Idtype { get; set; }

    public int? Idpartner { get; set; }

    public string Login { get; set; }

    public string Password { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public virtual ICollection<Arrival> ArrivalCreatorNavigations { get; set; } = new List<Arrival>();

    public virtual ICollection<Arrival> ArrivalIdAcceptanceClerkNavigations { get; set; } = new List<Arrival>();

    public virtual ICollection<Driver> Drivers { get; set; } = new List<Driver>();

    public virtual Partner IdpartnerNavigation { get; set; }

    public virtual UserType IdtypeNavigation { get; set; }

    public virtual ICollection<Outbound> Outbounds { get; set; } = new List<Outbound>();
}