<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="res\icons\Logo.png" />
    <None Remove="res\icons\menu.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="pages\partner\" />
    <Folder Include="pages\admin\" />
    <Folder Include="pages\manager\" />
    <Folder Include="pages\skladWorker\" />
    <Folder Include="pages\arrivalOutbound\" />
    <Folder Include="pages\driver\" />
    <Folder Include="windows\" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="res\icons\Logo.png" />
    <Resource Include="res\icons\menu.jpg" />
  </ItemGroup>

</Project>
